services:
  - type: web
    name: jarro-tiktok
    runtime: node
    rootDir: tiktok-server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TIKTOK_USER
        value: iuripiragibe
      - key: META
        value: 2000
