/* Lista de B-rolls, na ordem em que entram em cada episódio.
 * tipo TELA  = tela cheia (cobre o talking head).
 * tipo SOBRE = sobreposição (selo, nome, contador, marcador) sobre o talking head.
 * cue = trecho da narração em que o clipe entra.
 * Os ids (E1-01, E1-02...) são atribuídos automaticamente pela ordem. */

const T = (t, slug, d, p, x = {}) => ({ tipo: 'TELA', t, slug, d, p, ...x });
const O = (t, slug, d, p, x = {}) => ({ tipo: 'SOBRE', t, slug, d, p, ...x });
const selo = (slug, cat, fonte, cue, d = 5, pos) => O('selo', 'selo-' + slug, d, { cat, fonte, pos }, { cue });
const nome = (slug, nm, papel, cue, d = 5) => O('nome', 'nome-' + slug, d, { nome: nm, papel }, { cue });
const cap = (num, linhas, cue, somber) => T('capitulo', 'capitulo-' + num.toLowerCase(), 4, { num, linhas }, { cue, somber });
const loop = (slug, estado, num, texto, cue, d = 6, rotulo) => O('loop', slug, d, { estado, num, texto, rotulo }, { cue });

/* ====================================================================
 * PARTE 1 — O CURSO INTRODUTÓRIO
 * ==================================================================== */
const LIFTON = [
  { t: 'Controle do meio', d: ['O grupo controla o que entra e o que sai:', 'informação, convivência, tempo.'] },
  { t: 'Manipulação mística', d: ['O planejado é apresentado como espontâneo,', 'ou como sinal do destino.'] },
  { t: 'Exigência de pureza', d: ['O mundo se divide entre puro e impuro.', 'Você nunca é puro o suficiente.'] },
  { t: 'Culto da confissão', d: ['Você confessa seus defeitos ao grupo.', 'O grupo guarda. O grupo sempre guarda.'] },
  { t: 'Ciência sagrada', d: ['A doutrina é a verdade final.', 'De preferência, com cara de ciência.'] },
  { t: 'Linguagem carregada', d: ['Vocabulário próprio e frases prontas', 'que encerram qualquer discussão.'] },
  { t: 'Doutrina acima da pessoa', tl: ['Doutrina acima', 'da pessoa'], d: ['Se a sua experiência contradiz a doutrina,', 'o problema é a sua experiência.'] },
  { t: 'Dispensação da existência', tl: ['Dispensação', 'da existência'], d: ['Quem está fora vale menos.', 'Às vezes, não vale nada.'] }
];
const LIFTON_CUES = [
  'Primeiro, controle do meio.', 'Segundo, manipulação mística.', 'Terceiro, exigência de pureza.', 'Quarto, culto da confissão.',
  'Quinto, ciência sagrada.', 'Sexto, linguagem carregada.', 'Sétimo, doutrina acima da pessoa.', 'Oitavo, dispensação da existência.'
];

const EP1 = [
  T('chale230', 'chale-duas-e-meia', 10, {}, { cue: 'Madrugada de 10 de outubro de 1992... uma sócia acorda com três pessoas na porta.' }),
  T('etimologia', 'etimologia-dissidente', 8, { palavra: 'Dissidente', raiz: 'dissidere', sentido: 'sentar-se à parte', nota: 'Ela tinha conversado com alguém que mudou de cadeira.', gag: 'cadeira' }, { cue: 'Dissidente vem do latim dissidere: sentar-se à parte.' }),
  selo('marie-claire', 'reportagem', 'Revista Marie Claire nº 68 · novembro de 1996', 'O relato está numa reportagem da revista Marie Claire...'),
  T('etimologia', 'etimologia-liminar', 8, { palavra: 'Liminar', raiz: 'limen', sentido: 'soleira, a entrada da porta', nota: 'Decisão provisória, dada antes do fim do processo.', gag: 'soleira' }, { cue: 'Liminar vem do latim limen: soleira, a entrada da porta.' }),
  T('citacao', 'citacao-nao-damos-entrevista', 8, { linhas: ['Podem publicar o que quiserem,', 'não damos entrevista.'], autor: '— diretor do movimento, à revista Marie Claire (1996)', cat: 'reportagem' }, { cue: 'Procurado pela revista, um diretor do movimento respondeu assim...', fonte: 'Revista Marie Claire nº 68, novembro de 1996', cat: 'reportagem' }),
  T('numeros', 'numeros-movimento-hoje', 8, { titulo: 'O movimento, hoje, segundo o próprio site', itens: [{ v: 1600, pre: 'R$ ', label: ['curso de entrada'] }, { v: 9, suf: ' anos', label: ['idade mínima'] }, { texto: 'NÃO', label: ['é religião,', 'segundo o site'] }] }, { cue: 'Esse movimento existe até hoje... O curso de entrada custa 1.600 reais e aceita alunos a partir de nove anos.', fonte: 'Site oficial do movimento · página atualizada em 31/08/2026', cat: 'org' }),
  T('numeros', 'numeros-outra-escola', 8, { titulo: 'Outra escola de filosofia, segundo ela mesma', itens: [{ texto: '1957', label: ['fundada em', 'Buenos Aires'] }, { v: 54, label: ['países'] }, { texto: '400+', label: ['cidades'] }] }, { cue: 'Em 1957, em Buenos Aires, nasceu outra escola de filosofia. Hoje ela diz estar em 54 países.', fonte: 'Anuário Internacional 2023 da organização', cat: 'org' }),
  selo('el-espanol', 'testemunho', 'Ex-integrante ao jornal El Español · 31/12/2022', 'Em 2022, uma ex-integrante contou ao jornal espanhol El Español...'),
  O('aguias', 'contador-aguias-1', 6, { n: 1 }, { cue: 'Diante de uma águia. Guarde essa águia. Ela não é a última.' }),
  T('checklist', 'nenhuma-condenada', 9, { titulo: 'O que existe e o que não existe', itens: [{ t: 'Condenação das duas, como organização', ok: false, s: 'nenhuma' }, { t: 'Processo por difamação vencido por uma delas', ok: true, s: 'existe' }, { t: 'Crime de seita no Brasil', ok: false, s: 'não existe' }, { t: 'Definição legal de seita', ok: false, s: 'não existe' }], size: 52 }, { cue: 'Nenhuma das duas organizações foi condenada, como organização... Não existe nem definição legal de seita.' }),
  T('comparacao', 'mito-x-realidade', 11, { esq: { titulo: 'O que se acha', itens: ['burro', 'carente', 'fanático', 'túnica num sítio', 'disco voador'] }, dir: { titulo: 'O que aparece', itens: ['curso de filosofia', 'café e biscoito', 'chalé no interior', 'um banco interno', 'um tribunal em Tóquio'] }, riscarEsq: true, size: 64, passo: 0.3 }, { cue: 'A maioria das pessoas acha que quem cai em seita é burro, carente ou fanático... A verdade passa por cursos de filosofia com café e biscoito.' }),
  T('numeros', 'trinta-e-um-anos', 7, { itens: [{ v: 31, suf: ' anos', label: ['para um tribunal do Paraná reconhecer', 'confissões arrancadas sob tortura'] }], size: 260 }, { cue: 'E termina num tribunal do Paraná que levou 31 anos para reconhecer...', somber: true }),
  T('itens', 'nesta-serie', 9, { kicker: 'Nesta série', titulo: 'Três partes', itens: ['como gente inteligente entra', 'por que fica', 'como sai', 'e oito perguntas contra qualquer grupo'] }, { cue: 'Esta é a primeira de três partes. No caminho, você vai entender como gente inteligente entra nesses lugares...' }),
  loop('marcador-oito-perguntas-aberto', 'aberto', '00', ['Oito perguntas que funcionam', 'contra qualquer grupo (parte 3)'], 'E, no fim da terceira parte, eu vou te dar oito perguntas... Inclusive contra este canal.'),
  T('titulo', 'titulo-parte-1', 6, { parte: 'PARTE 1', sub: 'O CURSO INTRODUTÓRIO' }, { cue: 'Logo depois do gancho de abertura (cartela de título).' }),

  cap('I', ['Seita é a', 'religião dos outros'], 'Primeiro, um problema de vocabulário.'),
  T('etimologia', 'etimologia-seita', 10, { palavra: 'Seita', raizes: [{ raiz: 'sequi', sentido: 'seguir' }, { raiz: 'secare', sentido: 'cortar', obs: 'etimologia popular' }], nota: ['Em latim, secta também era escola de filosofia:', 'a seita dos estoicos, a seita dos epicuristas.'] }, { cue: '"Seita" vem do latim secta. Os dicionários ligam a palavra a sequi, seguir.' }),
  nome('weber-troeltsch', 'Max Weber e Ernst Troeltsch', 'sociólogos · início do século 20', 'No começo do século 20, os sociólogos Max Weber e Ernst Troeltsch...'),
  T('destaque', 'definicao-sociologica', 9, { kicker: 'Seita, segundo Weber e Troeltsch', linhas: ['Um grupo que [se separa] de uma igreja', 'e vive em [tensão] com o resto', 'da sociedade.'], nota: ['Piada antiga entre sociólogos da religião:', 'religião é uma seita que deu certo.'] }, { cue: 'Seita passou a ser um grupo que se separa de uma igreja e vive em tensão com o resto da sociedade.' }),
  T('citacao', 'citacao-codigo-penal-1890', 10, { linhas: ['…o espiritismo, a magia e seus sortilégios…', '…fascinar e subjugar a credulidade pública…'], autor: '— Código Penal de 1890, artigo 157', cat: 'oficial', size: 62, destaque: ['fascinar', 'subjugar'] }, { cue: 'O Código Penal de 1890, no artigo 157, punia quem praticasse "o espiritismo, a magia e seus sortilégios".', fonte: 'Decreto nº 847, de 1890', cat: 'oficial' }),
  T('linhatempo', 'linha-do-tempo-colecao', 11, { titulo: 'A coleção “Magia Negra”', anoSize: 60, eventos: [{ ano: '1890–1940', txt: ['polícia do Rio apreende', 'objetos de terreiros'] }, { ano: '1938', txt: ['Iphan tomba a coleção:', '1º bem do livro', 'de tombo etnográfico'] }, { ano: '2020', txt: ['21 de setembro: vai', 'para o Museu', 'da República'] }, { ano: '2023', txt: ['nome oficial passa a', '“Acervo Nosso Sagrado”'], destaque: true }] }, { cue: 'Entre 1890 e a década de 1940, a polícia do Rio de Janeiro apreendia objetos sagrados em terreiros...', fonte: 'Paula Fernandes da Silva (Anpege); Iphan', cat: 'academia' }),
  T('ficha', 'patrimonio-e-prova', 10, { cabecalho: 'MUSEU DA POLÍCIA · RIO DE JANEIRO', titulo: ['Coleção “Magia Negra”'], campos: [{ l: 'CONTEÚDO', v: 'imagens de santos, espadas, anéis' }, { l: 'ORIGEM', v: 'apreensões em terreiros' }, { l: 'NO MESMO MUSEU', v: 'armas brancas, toxicologia, jogos de azar' }], carimbos: [{ t: 'Patrimônio nacional', cor: 'blue', x: 520, y: 560, r: -8, size: 64 }, { t: 'Prova de crime', cor: 'red', x: 700, y: 670, r: 5, size: 64 }], nota: 'Ilustração. Fontes: Paula Fernandes da Silva (Anpege); Iphan, 1938.' }, { cue: 'Durante décadas, os mesmos objetos foram, ao mesmo tempo, patrimônio nacional e prova de crime.' }),
  T('etiqueta', 'etiqueta-acervo-nosso-sagrado', 9, { antes: { titulo: ['MAGIA', 'NEGRA'], sub: ['Museu da Polícia · RJ'] }, depois: { titulo: ['ACERVO NOSSO', 'SAGRADO'], sub: ['Museu da República · 2023'] }, nota: 'Saída do museu da polícia em 21/09/2020, após a campanha Liberte Nosso Sagrado.' }, { cue: 'Os objetos só saíram de lá em 21 de setembro de 2020... Passou a ser "Acervo Nosso Sagrado".' }),
  loop('marcador-magia-negra', 'aberto', '', ['“Magia negra”'], 'Guarde a expressão "magia negra". Ela volta. Não neste episódio, mas volta.', 6, 'GUARDE ESTA EXPRESSÃO'),
  T('comparacao', 'crenca-x-comportamento', 8, { esq: { titulo: 'Esta série não julga', itens: ['crença'], size: 130 }, dir: { titulo: 'Esta série olha', itens: ['comportamento'], size: 130 }, riscarEsq: true, rodape: ['A Constituição garante a liberdade de crença.', 'Eu não pretendo discutir com ela.'] }, { cue: 'Por isso, nesta série, a gente não vai julgar crença... A gente vai olhar comportamento.' }),

  cap('II', ['A invenção da', 'lavagem cerebral'], 'Setembro de 1950, primeiro ano da Guerra da Coreia.'),
  T('jornal', 'jornal-brain-washing', 7, { nota: 'Ilustração. Edward Hunter, Miami News, setembro de 1950.' }, { cue: 'O jornalista americano Edward Hunter publica no Miami News um artigo sobre técnicas chinesas de brain-washing.' }),
  nome('edward-hunter', 'Edward Hunter', ['jornalista · antes, OSS: o serviço de', 'inteligência que daria origem à CIA'], 'Antes de virar especialista em Guerra Fria, Hunter tinha passado a Segunda Guerra no OSS...', 6),
  T('linhatempo', 'linha-do-tempo-lavagem-cerebral', 11, { titulo: 'Lavagem cerebral, uma cronologia', eventos: [{ ano: '1950', txt: ['Hunter populariza', '“brain-washing”'] }, { ano: '1953', txt: ['fim da guerra:', '21 prisioneiros', 'não voltam'] }, { ano: '1956', txt: ['Exército dos EUA:', 'um equívoco', 'popular'], destaque: true }, { ano: '1961', txt: ['Lifton publica', 'os oito critérios'] }] }, { cue: 'Quando a guerra terminou, em 1953... Em 1956, o próprio Exército americano publicou um relatório chamando a lavagem cerebral de equívoco popular.', fonte: 'Exército dos EUA (1956); Wellcome Collection; Daniel Pick', cat: 'oficial' }),
  T('schein', 'schein-tres-etapas', 9, { nota: ['Edgar Schein, depois: MIT, cultura organizacional.', 'Não é uma piada. A piada é que não é uma piada.'] }, { cue: 'O psicólogo Edgar Schein... descongelar a identidade antiga, mudar, recongelar a nova.' }),
  nome('lifton', 'Robert Jay Lifton', 'psiquiatra · oito critérios do ambiente totalista (1961)', 'O psiquiatra Robert Jay Lifton entrevistou ocidentais e chineses...'),
  ...LIFTON.map((o, i) => T('lista8', `lifton-criterio-${i + 1}`, 6, { titulo: 'Os oito critérios de Lifton', itens: LIFTON, ativo: i + 1 }, { cue: LIFTON_CUES[i] })),
  T('lista8', 'lifton-visao-geral', 7, { titulo: 'Os oito critérios de Lifton', itens: LIFTON, ativo: 0 }, { cue: 'Esses critérios descrevem tendências, não um tipo de organização.' }),
  T('checklist', 'onde-mais-aparece', 10, { titulo: 'Onde mais você reconheceu a lista', itens: [{ t: 'Antigo emprego' }, { t: 'Família' }, { t: 'Grupo de WhatsApp do condomínio' }], nota: ['Todo grupo humano tem um pouco disso. A pergunta é quanto.', 'E o que acontece quando você tenta ir embora.'] }, { cue: 'Se você ouviu essa lista e pensou no seu antigo emprego, na sua família ou no grupo de WhatsApp do condomínio...' }),

  cap('III', ['Ninguém', 'é burro'], 'Antes de seguir, uma correção de rota.'),
  T('dateline', 'dateline-toquio-1995', 9, { lugar: 'TÓQUIO · METRÔ', data: '20.03.1995', sub: ['Ataque com gás sarin da Aum Shinrikyo.', 'O grupo recrutava estudantes e profissionais formados,', 'entre eles químicos e médicos.'] }, { cue: 'A Aum Shinrikyo, a seita japonesa que atacou o metrô de Tóquio com gás sarin em 1995...', somber: true }),
  T('itens', 'quem-entra', 10, { kicker: 'Quem entra, segundo décadas de pesquisa', titulo: 'Uma fase de transição', itens: ['mudou de cidade', 'terminou um relacionamento', 'perdeu alguém', 'entrou na faculdade'], nota: 'Comum: escolaridade acima da média e vontade de que a vida signifique alguma coisa.' }, { cue: 'Quem entra costuma estar numa fase de transição: mudou de cidade, terminou um relacionamento...', fonte: 'Eileen Barker (1984); literatura sobre recrutamento', cat: 'academia' }),
  T('carimbo', 'inteligencia-nao-protege', 7, { linhas: ['Inteligência'], carimbo: 'NÃO PROTEGE', cSize: 120, depois: ['Um sistema de ideias complicado parece mais sério', 'para quem gosta de ideias complicadas.'] }, { cue: 'Inteligência não protege. Às vezes atrapalha.' }),
  T('dateline', 'terca-feira-qualquer', 8, { lugar: 'ANÚNCIO PATROCINADO', data: 'TERÇA-FEIRA', sub: ['Palestra gratuita sobre filosofia estoica.', 'Ou meditação. Ou desenvolvimento mental.', 'Ou como lidar com as emoções.'] }, { cue: 'Você é recrutado num anúncio patrocinado. Imagine uma terça-feira.' }),
  T('cracha', 'love-bombing', 9, { frases: ['Que bom que você veio!', 'Adorei a sua pergunta.', 'Lembro do seu nome, sim.', 'Fica para o café?', 'Você tem uma energia ótima.', 'Volta na terça que vem?'] }, { cue: 'As pessoas são simpáticas. Muito simpáticas. Lembram do seu nome... love bombing, bombardeio de amor.' }),
  T('ficha', 'ficha-curso-introdutorio', 11, { x: 240, w: 860, cabecalho: 'FICHA DE INSCRIÇÃO', titulo: ['Curso introdutório'], campos: [{ l: 'NOME', v: 'você' }, { l: 'VALOR', v: 'não é caro' }, { l: 'DURAÇÃO', v: 'é só um começo' }, { l: 'PRÓXIMA ETAPA', v: 'a gente conversa depois' }], cafe: true, nota: 'Ninguém sai de casa para entrar numa seita. As pessoas saem para estudar estoicismo.' }, { cue: 'A palestra é boa. De verdade. No fim, alguém comenta que existe um curso introdutório. Não é caro. É só um começo.' }),
  T('escada', 'pe-na-porta', 9, { kicker: 'PÉ NA PORTA', degraus: [['palestra', 'grátis'], ['curso', 'introdutório'], ['próximo', 'nível'], ['mais um', 'nível'], ['?']], nota: 'Robert Cialdini, As Armas da Persuasão (1984).' }, { cue: 'Psicólogos sociais têm nome para esse "só um começo": a técnica do pé na porta.' }),
  nome('cialdini', 'Robert Cialdini', 'psicólogo social · As Armas da Persuasão (1984)', 'Robert Cialdini descreveu o mecanismo em 1984...'),

  cap('IV', ['Por fora'], 'A Nova Acrópole foi fundada em 1957, em Buenos Aires...'),
  nome('livraga', 'Jorge Ángel Livraga Rizzi', 'fundador da Nova Acrópole · 1930–1991', 'pelo argentino Jorge Ángel Livraga Rizzi.'),
  T('esoterico', 'esoterico-exoterico', 8, {}, { cue: 'Esotérico vem do grego esōterikós: de dentro... O ensino para o público de fora se chamava exotérico.' }),
  T('numeros', 'numeros-nova-acropole', 8, { titulo: 'Nova Acrópole, segundo ela mesma', itens: [{ v: 54, label: ['países'] }, { texto: '400+', label: ['cidades'] }, { texto: '70+', label: ['escolas no Brasil'] }] }, { cue: 'Segundo ela mesma, hoje está em 54 países e em mais de 400 cidades. No Brasil, diz ter mais de 70 escolas.', fonte: 'Anuário Internacional 2023; canal oficial da organização', cat: 'org' }),
  T('itens', 'objetivos-oficiais', 8, { kicker: 'Objetivos oficiais', titulo: '“Filosofia à maneira clássica”', itens: ['fraternidade universal', 'estudo comparado de filosofias, ciências, religiões e artes', 'desenvolvimento do indivíduo'], numerado: true }, { cue: 'A proposta pública é a "filosofia à maneira clássica"... Os objetivos oficiais são três.', fonte: 'Carta de princípios da organização', cat: 'org' }),
  nome('lucia-helena-galvao', 'Lúcia Helena Galvão', 'professora da Nova Acrópole desde 1989', '(trecho opcional) O rosto público mais conhecido da Nova Acrópole no Brasil...'),
  selo('mangue-jornalismo', 'reportagem', 'Mangue Jornalismo · 2025', '(trecho opcional) Em 2025, segundo o site Mangue Jornalismo, a Prefeitura de Aracaju...'),
  T('linhatempo', 'linha-do-tempo-pro-vida', 11, { titulo: 'Pró-Vida: a origem', eventos: [{ ano: '1977', txt: ['“treinamento mental”', 'para 14 amigos,', 'na Mooca'] }, { ano: '1978', txt: ['fundação da', 'Pró-Mente'] }, { ano: '1979', txt: ['o nome muda', 'para Pró-Vida'] }, { ano: '1981', txt: ['morte de', 'Celso Charuri,', 'aos 41 anos'] }] }, { cue: 'Em outubro de 1977, em São Paulo, um ginecologista chamado Celso Charuri reuniu catorze amigos...', fonte: 'Pró-Vida (site oficial); dissertação USP (2004)', cat: 'org' }),
  nome('celso-charuri', 'Celso Charuri', 'ginecologista · fundador da Pró-Vida · 1940–1981', 'um ginecologista chamado Celso Charuri...'),
  T('troca', 'pro-mente-pro-vida', 7, { prefixo: 'PRÓ-', de: 'MENTE', para: 'VIDA', anoDe: '1978', anoPara: '1979', nota: 'A mente continuou envolvida.' }, { cue: 'A Pró-Mente virou Pró-Vida. A mente continuou envolvida.' }),
  T('numeros', 'numeros-pro-vida', 9, { titulo: 'Pró-Vida, segundo o próprio site', itens: [{ v: 13, label: ['países'] }, { v: 9, label: ['níveis'] }, { v: 1600, pre: 'R$ ', label: ['Semana de Básico'] }, { v: 9, suf: ' anos', label: ['idade mínima'] }] }, { cue: 'Hoje, segundo o próprio site... O programa tem nove níveis. A Semana de Básico custa 1.600 reais...', fonte: 'provida.net · página atualizada em 31/08/2026', cat: 'org' }),
  T('numeros', 'escolas-doadas', 8, { itens: [{ v: 16, label: ['escolas profissionalizantes', 'doadas, segundo o movimento'] }, { texto: 'SENAI-SP', label: ['confirma unidades com', 'Charuri como patrono'] }] }, { cue: 'O movimento também faz ação social. Diz ter doado 16 escolas profissionalizantes, e o SENAI de São Paulo confirma...', fonte: 'Pró-Vida (Central Geral do Dízimo); página do SENAI-SP', cat: 'oficial' }),
  T('checklist', 'nada-disso-e-ilegal', 9, { titulo: 'Pausa para a observação mais importante', itens: [{ t: 'Curso pago', s: 'legal' }, { t: 'Clube de campo', s: 'legal' }, { t: 'Ensinar Platão', s: 'ótimo' }, { t: 'Doar escola', s: 'ótimo' }], nota: 'É exatamente essa a sensação de quem está entrando.' }, { cue: 'Nada disso é ilegal, estranho ou necessariamente ruim. Curso pago é legal...' }),

  cap('V', ['A anomalia'], 'Agora, a anomalia.'),
  T('fluxo', 'se-fosse-cinema', 7, { kicker: 'Se lavagem cerebral fosse aquilo do cinema', etapas: [{ t: ['Entra quem', 'assiste à palestra'], size: 56 }, { t: ['Sai', 'um fiel'], size: 56, destaque: true }], bh: 240, nota: 'Seria o negócio mais eficiente do planeta.', notaY: 860 }, { cue: 'Se lavagem cerebral é aquilo do cinema... Entra quem assiste à palestra. Sai um fiel.' }),
  nome('eileen-barker', 'Eileen Barker', 'socióloga britânica · London School of Economics', 'No fim dos anos 1970, a socióloga britânica Eileen Barker resolveu medir isso.'),
  T('itens', 'barker-sete-anos', 8, { kicker: 'Eileen Barker · fim dos anos 1970', titulo: ['Quase sete anos', 'contando'], itens: ['quem entrava', 'quem ficava', 'quem ia embora'], nota: 'O resultado fica para o próximo episódio.' }, { cue: 'e passou quase sete anos contando quem entrava, quem ficava e quem ia embora.' }),
  loop('marcador-anomalia-aberto', 'aberto', '01', ['Por que algumas pessoas ficam por décadas?', 'E por que acordar uma sócia às 2h30?'], 'Guarde essa contradição. Se a técnica não funciona na maioria das pessoas...', 7),
  T('proximo', 'proximo-episodio-parte-2', 10, { parte: 'PARTE 2', titulo: ['Os andares', 'de cima'], itens: ['um curso em que era proibido anotar', 'uma comissão que decidia quem subia', 'um chalé que fica para trás quando você sai', 'uniformes, brigadas e um juramento diante de uma águia'] }, { cue: 'No próximo episódio, a gente entra. Vai subir os andares, um por um...' })
];

/* ====================================================================
 * PARTE 2 — OS ANDARES DE CIMA
 * ==================================================================== */
const ANDARES = ['O compromisso pequeno', 'O vocabulário', 'O segredo', 'Quem sobe é escolhido', 'Dinheiro e patrimônio', 'Sair custa caro'];
const funil = (k, nota, cue) => T('funil', `funil-andar-${k}`, 6, { andares: ANDARES, ativo: k, nota }, { cue });

const EP2 = [
  T('folha', 'folha-respeitar-o-lider', 14, { frase: 'Eu preciso aprender a respeitar o meu líder.', linhas: 12, nota: ['Reconstituição gráfica. Frase relatada pela imprensa local, Maranhão, 2026.'] }, { cue: 'Maranhão, 2026. Numa operação de resgate... folhas de papel com uma única frase, escrita à mão, várias vezes.', somber: true }),
  T('titulo', 'titulo-parte-2', 6, { parte: 'PARTE 2', sub: 'OS ANDARES DE CIMA' }, { cue: 'Ninguém chega a lugar nenhum de uma vez. Chega por andares. (cartela de título)' }),
  T('itens', 'no-episodio-anterior', 10, { kicker: 'No episódio anterior', itens: ['no Brasil, seita sempre foi a religião dos outros', 'lavagem cerebral: expressão da Guerra Fria, desmentida em 1956', 'gente inteligente entra, às vezes por ser inteligente', 'duas escolas de filosofia, vistas por fora'], size: 46, y0: 360 }, { cue: 'No primeiro episódio, a gente ficou na porta de entrada.' }),
  loop('marcador-anomalia-lembrete', 'aberto', '01', ['Por que algumas pessoas ficam por décadas?', 'E por que acordar uma sócia às 2h30?'], 'E ficou uma anomalia... E por que alguém acordaria uma sócia às duas e meia da manhã?'),

  cap('I', ['O funil'], 'Quase todo grupo de alta demanda funciona como um funil.'),
  T('funil', 'funil-visao-geral', 9, { andares: ANDARES, ativo: 0, nota: ['Na boca entra muita gente. Lá embaixo sai pouca:', 'exatamente a que o grupo queria.'] }, { cue: 'Na boca do funil entra muita gente. Lá embaixo sai pouca.' }),
  T('bite', 'modelo-bite', 7, {}, { cue: 'O psicólogo Steven Hassan resumiu o que acontece lá dentro em quatro letras: BITE.' }),
  nome('steven-hassan', 'Steven Hassan', 'psicólogo · modelo BITE', 'O psicólogo Steven Hassan...'),
  funil(1, ['O pé na porta: a palestra, o curso introdutório,', 'o “é só um começo”.'], 'O primeiro andar você já conhece: o pé na porta.'),
  funil(2, 'O grupo começa a te dar palavras novas.', 'O segundo andar é o vocabulário.'),
  T('carimbo', 'duvida-yoes-bajos', 9, { antes: 'Escola de Yoga de Buenos Aires, segundo o Ministério Público argentino:', linhas: ['Dúvida'], carimbo: 'YOES BAJOS', cSize: 120, depois: ['os “eus inferiores”.', 'Quando a sua dúvida tem nome de defeito, você passa a ter defeitos.'] }, { cue: 'as dúvidas dos alunos tinham nome, segundo o Ministério Público argentino: yoes bajos.', fonte: 'Ministério Público Fiscal da Argentina', cat: 'oficial' }),
  funil(3, 'Os níveis de cima são revelados aos poucos.', 'O terceiro andar é o segredo.'),
  T('comparacao', 'anotar-proibido', 9, { esq: { titulo: 'Faculdade de Direito', alt: 2, itens: [['anotar:', 'obrigatório'], ['quem lembra:', 'ninguém']] }, dir: { titulo: 'Pró-Vida, anos 1990', alt: 2, itens: [['anotar:', 'proibido'], ['quem lembra:', 'trinta anos depois']] } }, { cue: 'Na Pró-Vida dos anos 1990, segundo a repórter da Marie Claire que se infiltrou no curso, era proibido anotar.', fonte: 'Revista Marie Claire nº 68, 1996', cat: 'reportagem' }),
  T('itens', 'conteudo-dos-niveis', 11, { kicker: 'Dissertação de mestrado · Instituto de Psicologia da USP · 2004', titulo: 'O que tinha nos níveis', itens: ['níveis iniciáticos', 'a “Chave de Prata”', 'a “Tela Mental”, com E = mc²', 'pirâmides', 'imposição de mãos', 'exercícios de levitação e clarividência'] }, { cue: 'Em 2004, uma dissertação de mestrado no Instituto de Psicologia da USP... descreveu o conteúdo.', fonte: 'Ricardo José Barbosa da Silva, USP (2004)', cat: 'academia' }),
  T('citacao', 'citacao-usp-caracteristicas', 9, { linhas: ['…reveste-se das características', 'de seita.'], autor: ['— Ricardo José Barbosa da Silva, dissertação USP (2004)', 'Ressalva: o autor declara linha teórica crítica;', 'o movimento se define como filosófico.'], cat: 'academia' }, { cue: 'O autor concluiu que a Pró-Vida se reveste das características de seita. Uma ressalva necessária...' }),
  T('emc2', 'e-igual-mc2', 7, {}, { cue: 'E igual a m c ao quadrado é, provavelmente, a equação mais citada por gente que nunca fez a conta.' }),
  nome('gerald-bronner', 'Gérald Bronner', 'sociólogo francês', 'Sobre a Nova Acrópole, o sociólogo francês Gérald Bronner a cita...'),
  selo('nova-acropole-rejeita', 'org', 'A Nova Acrópole rejeita a classificação de seita', 'A Nova Acrópole rejeita a classificação de seita.'),
  funil(4, 'Na Pró-Vida de 1996, uma comissão decidia quem avançava.', 'O quarto andar: quem sobe é escolhido.'),
  T('sequencia', 'introducao-depois-do-avancado', 9, { kicker: 'PRÓ-VIDA, SEGUNDO A REPORTAGEM DE 1996', etapas: ['BÁSICO', 'AVANÇADO 1', 'INTRODUÇÃO', ['AVANÇADOS', '2 A 7']], alvo: 2, nota: ['Sim. A Introdução vinha depois do Avançado 1.', 'Eu li três vezes.'] }, { cue: 'Depois do Básico vinham o Avançado 1, a Introdução e os Avançados de 2 a 7. Sim. A Introdução vinha depois do Avançado 1.', fonte: 'Revista Marie Claire nº 68, 1996', cat: 'reportagem' }),
  funil(5, 'Desde 12 de outubro de 1979: Central Geral do Dízimo.', 'O quinto andar é o dinheiro e o patrimônio.'),
  T('etimologia', 'etimologia-dizimo', 8, { palavra: 'Dízimo', raiz: 'decimus', sentido: 'a décima parte', nota: ['Num movimento que, segundo ele mesmo, não é religião.', 'Pelo menos a matemática é laica.'], gag: 'decimo' }, { cue: 'Dízimo vem do latim decimus, a décima parte.' }),
  T('ficha', 'ficha-chale', 11, { cabecalho: 'MODELO DESCRITO EM PROCESSO NO TJSP · 2019', titulo: ['Clube do movimento'], campos: [{ l: 'TÍTULO DO CLUBE', v: 'R$ 30 mil' }, { l: 'DIREITO DE USO DO CHALÉ', v: 'mais R$ 40 mil' }, { l: 'QUEM PODE', v: 'restrito a filiados' }, { l: 'SE VOCÊ SAI DO GRUPO', v: 'você sai do chalé' }], carimbos: [{ t: 'Cláusula de fidelidade', cor: 'red', x: 560, y: 690, r: -7, size: 58 }], nota: 'Ilustração. Fontes: TJSP, agravo de instrumento (2019); Marie Claire (1996).' }, { cue: 'Um processo de 2019 no Tribunal de Justiça de São Paulo mostra que o modelo continuava... Traduzindo: se você sai do grupo, você sai do chalé.' }),
  funil(6, 'Sair custa caro.', 'O sexto andar: sair custa caro.'),
  T('barras', 'chale-devolucao-revenda', 9, { titulo: 'Um chalé devolvido em 1992', itens: [{ label: ['pago à', 'ex-integrante'], v: 5000, pre: 'US$ ', txt: 'US$ 5 mil' }, { label: ['revenda,', 'segundo ela'], v: 25000, pre: 'US$ ', txt: 'US$ 25 mil', cor: 'red' }], reserva: 380 }, { cue: 'Recebeu cerca de 5 mil dólares pela devolução do chalé. Segundo ela, o chalé foi revendido por 25 mil.', fonte: 'Relato de ex-integrante à revista Marie Claire nº 68, 1996', cat: 'testemunho' }),
  T('citacao', 'citacao-nao-agredimos', 7, { linhas: ['…não agredimos os que', 'nos contrariam.'], autor: '— Pró-Vida, à Gazeta Pará-minense (06/06/2013)', cat: 'org' }, { cue: 'Em 2013, a um jornal de Minas Gerais, a Pró-Vida disse... "não agredimos os que nos contrariam".', fonte: 'Gazeta Pará-minense, 06/06/2013', cat: 'org' }),

  cap('II', ['O círculo', 'interno'], 'Na Nova Acrópole, o que ex-integrantes de vários países descrevem acontece depois dos cursos.'),
  selo('ex-integrantes', 'testemunho', ['Relatos de ex-integrantes da França,', 'da Polônia, da Espanha e do Uruguai'], 'Atenção: daqui em diante, o que vem é testemunho de ex-integrantes...', 7),
  T('organograma', 'organograma-forcas-vivas', 11, {}, { cue: 'Eles relatam um círculo interno chamado Forças Vivas... E existiria um Manual do Dirigente.', fonte: 'Relatos de ex-integrantes (França, Polônia, Espanha, Uruguai)', cat: 'testemunho' }),
  T('citacao', 'citacao-miviludes', 9, { linhas: ['Piramidal e militarmente', 'hierarquizada.'], autor: ['— Miviludes, à France 3 Occitanie (2018), tradução livre', 'Resposta da Nova Acrópole: alvo de “rumores”.'], cat: 'oficial' }, { cue: 'Em 2018, a Miviludes disse à TV pública France 3 que a organização é "piramidal e militarmente hierarquizada".', fonte: 'Miviludes à France 3 Occitanie, 2018', cat: 'oficial' }),
  T('itens', 'relato-el-espanol', 11, { kicker: 'El Español · 31/12/2022 · ex-integrante, dez anos no grupo', itens: ['banhos em rio gelado', 'tapas', 'investidura de braço erguido diante da “Águila Solar”', '“buracos energéticos” tratados com laser'], nota: 'A reportagem ouviu a organização.', y0: 330 }, { cue: 'Em 2022, o jornal espanhol El Español publicou o relato de uma ex-integrante que passou dez anos no grupo.', fonte: 'El Español, 31/12/2022', cat: 'testemunho' }),
  O('aguias', 'contador-aguias-1-lembrete', 5, { n: 1 }, { cue: 'É a águia do primeiro episódio.' }),
  T('citacao', 'citacao-relatorio-vivien', 10, { linhas: ['Sob aparências liberais democráticas', 'se perfila um movimento com', 'simpatias totalitárias.'], autor: '— Relatório Vivien, França (1983), tradução livre', cat: 'oficial', size: 68 }, { cue: 'Em 1983, um relatório encomendado pelo governo francês, o Relatório Vivien, escreveu...', fonte: 'Relatório Vivien, 1983', cat: 'oficial' }),
  nome('goodrick-clarke', 'Nicholas Goodrick-Clarke', 'historiador britânico · ocultismo e nazismo', 'O historiador britânico Nicholas Goodrick-Clarke...'),
  T('balanca', 'balanca-dois-lados', 12, { esq: { titulo: 'ACUSAÇÕES', itens: ['Relatório Vivien (1983)', 'Goodrick-Clarke'] }, dir: { titulo: 'CONTRAPONTOS', itens: ['Antoine Faivre (1996)', 'Alain Bouchard (2013)', 'Universidade Laval', 'versão da organização'] }, nota: 'Os dois lados existem. Os tribunais ficam para o último episódio.' }, { cue: 'Agora, o outro lado, que existe. O historiador das religiões Antoine Faivre concluiu, em 1996...' }),
  selo('contrapontos', 'academia', ['Antoine Faivre (1996) · Alain Bouchard (2013)', 'Universidade Laval (Canadá)'], 'O historiador das religiões Antoine Faivre... Um centro de pesquisa da Universidade Laval...', 6),
  selo('humanista-laica', 'org', 'A Nova Acrópole se define como humanista, laica e apolítica', 'E a Nova Acrópole se define como uma associação humanista, laica e apolítica...'),

  cap('III', ['Quando o funil', 'encontra outro', 'objetivo'], 'Até aqui, estamos falando de chalés, uniformes e cursos sem caderno.'),
  T('tarjada', 'esquire-belo-horizonte', 9, { kicker: 'REVISTA AMERICANA · JANEIRO DE 1962', titulo: ['Os nove lugares mais seguros', 'em caso de guerra nuclear'], total: 9, revela: 4, nome: 'Belo Horizonte, Brasil', nota: 'Os outros oito ficam tarjados. Não interessam a esta história.' }, { cue: 'a revista Esquire tinha publicado uma lista dos nove lugares do mundo mais seguros em caso de guerra nuclear. Belo Horizonte estava na lista.', fonte: 'Jonestown Institute, San Diego State University', cat: 'academia' }),
  nome('jim-jones', 'Jim Jones', 'fundador do Templo do Povo · morou em Belo Horizonte em 1962', 'Em 1962, o fundador, Jim Jones, se mudou com a família para Belo Horizonte.'),
  T('dateline', 'dateline-jonestown', 7, { lugar: 'JONESTOWN · GUIANA', data: '1978', sub: ['Mais de 900 seguidores de Jim Jones morreram.'] }, { cue: 'Em 1978, na Guiana, mais de 900 seguidores de Jim Jones morreram em Jonestown.', somber: true }),
  T('dateline', 'dateline-buenos-aires-2022', 8, { lugar: 'BUENOS AIRES · ARGENTINA', data: 'AGO. 2022', sub: ['Cerca de 50 buscas ligadas à Escola de Yoga de Buenos Aires,', 'com cooperação dos Estados Unidos.'] }, { cue: 'Agosto de 2022. A polícia argentina, com cooperação dos Estados Unidos, faz cerca de cinquenta buscas...', somber: true }),
  T('itens', 'acusacao-escola-de-yoga', 11, { kicker: 'A acusação, segundo o Ministério Público', itens: ['associação ilícita', 'tráfico de pessoas para exploração sexual', 'lavagem de dinheiro', 'sedação com psicofármacos numa clínica do grupo', 'o “banquito”: um sistema interno de dívidas'], nota: 'Os acusados negam e respondem em liberdade.', y0: 330 }, { cue: 'A acusação é de associação ilícita, tráfico de pessoas para exploração sexual e lavagem de dinheiro...', fonte: 'Ministério Público Fiscal da Argentina', cat: 'oficial', somber: true }),
  T('linhatempo', 'linha-do-tempo-escola-de-yoga', 10, { titulo: 'Escola de Yoga de Buenos Aires: o processo', anoSize: 60, eventos: [{ ano: '2022', txt: ['cerca de', '50 buscas'] }, { ano: '2023', txt: ['câmara federal', 'anula o envio', 'a julgamento'] }, { ano: '2025', txt: ['17 processados de novo;', 'caso vai a', 'julgamento oral'] }, { ano: 'MAI. 2026', txt: ['mais três', 'dirigentes', 'processados'] }], nota: 'O julgamento ainda não aconteceu. Os acusados negam.' }, { cue: 'O caso tem idas e vindas. Em 2023, uma câmara federal anulou...', somber: true }),

  cap('IV', ['Abadiânia,', 'Maranhão,', 'Shakahola'], 'No Brasil, o caso mais brutal de líder espiritual não envolve curso nenhum.', true),
  T('dateline', 'dateline-abadiania', 8, { lugar: 'ABADIÂNIA · GOIÁS', data: 'DEZ. 2018', sub: ['Mulheres começam a relatar, em rede nacional,', 'abusos sexuais cometidos pelo médium João de Deus.'] }, { cue: 'Em dezembro de 2018, mulheres começaram a relatar, em rede nacional, abusos sexuais cometidos pelo médium João de Deus...', somber: true }),
  T('barras', 'penas-joao-de-deus', 10, { titulo: 'João de Deus: as penas', itens: [{ label: ['1ª instância', '(17 ações)'], v: 489.33, txt: '489 anos e 4 meses' }, { label: ['2ª instância'], v: 214, txt: 'cerca de 214 anos' }, { label: ['limite de', 'cumprimento'], v: 40, txt: '40 anos' }], xBar: 560, reserva: 600, nota: 'Soma das condenações por 56 vítimas. Ele está em prisão domiciliar.' }, { cue: 'Somadas, as penas chegaram a 489 anos e 4 meses. Em segunda instância, foram readequadas para cerca de 214 anos...', fonte: 'Tribunal de Justiça de Goiás', cat: 'judicial', somber: true }),
  T('dateline', 'dateline-paco-do-lumiar', 8, { lugar: 'PAÇO DO LUMIAR · MARANHÃO', data: 'ABR. 2026', sub: ['A Polícia Civil prende o pastor da Shekinah House Church,', 'investigado por crimes sexuais e estelionato.'] }, { cue: 'Abril de 2026. Paço do Lumiar, região metropolitana de São Luís...', somber: true }),
  T('numeros', 'resgate-maranhao', 9, { titulo: 'Maio de 2026 · operação do MTE, do MPT e da Polícia Federal', itens: [{ texto: '~40', label: ['pessoas resgatadas em', 'condição análoga à de escravo'] }, { texto: '12h+', label: ['jornadas,', 'sem pagamento'] }, { v: 17, label: ['pessoas com deficiência', 'e dependentes químicos'] }], nota: 'Investigação em curso.' }, { cue: 'Em maio, uma força-tarefa... resgatou cerca de 40 pessoas no local, em condição análoga à de escravo.', fonte: 'Operação MTE / MPT / PF; O Imparcial; O Cafezinho', cat: 'oficial', somber: true }),
  T('carimbo', 'doutrina-acima-da-pessoa', 9, { antes: 'As folhas do começo deste episódio:', linhas: ['Eu preciso aprender', 'a respeitar o meu líder.'], size: 110, carimbo: 'DOUTRINA ACIMA DA PESSOA', cSize: 64, cor: 'cream', rot: -5, depois: 'O sétimo critério de Lifton, no formato de castigo de escola.', apagar: true }, { cue: 'É o sétimo critério de Lifton, a doutrina acima da pessoa, no formato de castigo de escola.', somber: true }),
  selo('o-imparcial', 'reportagem', 'O Imparcial · O Cafezinho · maio de 2026', 'parte dos resgatados não se reconhece como vítima. Alguns tentaram voltar para o sítio.'),
  T('dateline', 'dateline-shakahola', 8, { lugar: 'FLORESTA DE SHAKAHOLA · QUÊNIA', data: '2023', sub: ['Até outubro de 2023, segundo um comitê do Senado queniano:', '428 corpos. Os processos continuam.'] }, { cue: 'E há o fundo do poço. Em 2023, na floresta de Shakahola, no Quênia...', somber: true }),

  cap('V', ['A anomalia,', 'resolvida'], 'Agora, de volta à anomalia do primeiro episódio.'),
  T('barras', 'barker-retencao', 10, { titulo: 'Workshops da Igreja da Unificação', sub: 'segundo Eileen Barker, The Making of a Moonie (1984)', itens: [{ label: ['participantes'], v: 100, txt: '100%' }, { label: ['ficaram mais de', 'uma semana'], v: 24, txt: 'menos de 25%' }, { label: ['membros em tempo', 'integral, um ano depois'], v: 5, txt: 'cerca de 5%', cor: 'red' }], xBar: 680, reserva: 420, nota: 'Taxa de retenção de uma academia em janeiro.' }, { cue: 'Barker acompanhou quem passava pelos workshops de recrutamento de dois dias... cerca de 5% continuavam membros em tempo integral.' }),
  T('linhatempo', 'tese-nos-tribunais', 10, { titulo: 'A tese da lavagem cerebral, posta à prova', eventos: [{ ano: '1984', txt: ['Barker publica', 'The Making', 'of a Moonie'] }, { ano: '1987', txt: ['APA rejeita relatório', 'coordenado por Singer:', 'falta de rigor'] }, { ano: '1990', txt: ['EUA contra Fishman:', 'juiz exclui Singer', 'como perita'], destaque: true }] }, { cue: 'Em 1987, a Associação Americana de Psicologia rejeitou um relatório coordenado pela psicóloga Margaret Singer...', fonte: 'APA (1987); Estados Unidos contra Fishman (1990)', cat: 'judicial' }),
  nome('margaret-singer', 'Margaret Singer', 'psicóloga · defensora da tese da lavagem cerebral nos tribunais', 'a psicóloga Margaret Singer, a principal defensora da tese da lavagem cerebral nos tribunais.'),
  T('carimbo', 'coisa-mais-chata', 7, { antes: 'Então lavagem cerebral não existe?', linhas: ['Existe uma coisa', 'mais chata.'], size: 190, carimbo: 'FUNCIONA MELHOR', cSize: 100, cor: 'amber' }, { cue: 'Então lavagem cerebral não existe? Existe uma coisa mais chata. E, por ser chata, funciona melhor.' }),
  nome('janja-lalich', 'Janja Lalich', 'socióloga · escolha limitada', 'A socióloga Janja Lalich chama isso de escolha limitada.'),
  T('escolha', 'escolha-limitada', 16, { passos: [{ t: ['MAIS UMA', 'PALESTRA'], custo: ['nada'] }, { t: ['PRÓXIMO', 'NÍVEL'], custo: ['o curso'] }, { t: ['CONTRIBUIR', 'COM A OBRA'], custo: ['o que já', 'foi investido'] }, { t: ['PEGAR O', 'CHALÉ'], custo: ['o chalé'] }, { t: ['VINTE ANOS', 'DEPOIS'], custo: ['a casa de campo,', 'os amigos, o casamento,', 'a explicação do mundo'] }] }, { cue: 'Assistir a mais uma palestra é razoável. Fazer o próximo nível é razoável... Até que um dia sair significa perder a casa de campo...' }),
  T('carimbo', 'o-chale-e-a-lavagem', 7, { linhas: ['O chalé'], size: 260, carimbo: 'É A LAVAGEM CEREBRAL', cSize: 92, depois: 'E nem tinha escritura.' }, { cue: 'O chalé é a lavagem cerebral. E nem tinha escritura.' }),
  T('fluxo', 'festinger-clarion', 11, { kicker: 'CHICAGO, 1954 · LEON FESTINGER, INFILTRADO', etapas: [{ t: ['21 DE', 'DEZEMBRO'], s: ['fim do mundo previsto:', 'uma inundação'] }, { t: ['DISCOS', 'VOADORES'], s: ['resgate vindo do', 'planeta Clarion'] }, { t: ['O MUNDO', 'NÃO ACABA'], s: ['22 de dezembro,', 'normalmente'] }, { t: ['OS MAIS', 'COMPROMETIDOS'], s: ['passam a pregar', 'mais do que antes'], destaque: true }], bh: 260 }, { cue: 'Em 1954, o psicólogo Leon Festinger se infiltrou num grupo da região de Chicago que esperava o fim do mundo...', fonte: 'Festinger, Riecken e Schachter, When Prophecy Fails (1956)', cat: 'academia' }),
  T('dissonancia', 'dissonancia-cognitiva', 7, {}, { cue: 'O nome técnico disso é dissonância cognitiva... O nome popular é "agora que eu já peguei o chalé".' }),
  T('janela', 'janela-dissidente', 9, {}, { cue: 'E isso responde à pergunta das duas e meia da manhã... E janela aberta, numa casa assim, se fecha de madrugada.' }),
  loop('marcador-anomalia-respondida', 'fechado', '01', ['Uma conversa com um dissidente', 'é uma janela aberta.'], 'Um dissidente é uma janela aberta.'),
  T('itens', 'todos-tinham-titulo', 7, { kicker: 'Até agora, todos tinham um título', itens: ['Mestre', 'Comandante Mundial', 'Anjo', 'Médium'], size: 76, gap: 110, y0: 380 }, { cue: 'Até agora, todos os personagens desta série tinham um título. Mestre. Comandante Mundial. Anjo. Médium.' }),
  loop('marcador-cacadores-aberto', 'aberto', '02', ['O erro mais grave desta série', 'foi de quem caçava seitas.'], 'Só que o erro mais grave desta série não foi cometido por um guru. Foi cometido por quem estava caçando seitas.', 7),
  T('proximo', 'proximo-episodio-parte-3', 10, { kicker: 'NO ÚLTIMO EPISÓDIO', parte: 'PARTE 3', titulo: ['A segunda', 'águia'], itens: ['uma cidade de praia no Paraná e fitas cassete', 'os tribunais da Nova Acrópole', 'um recibo em Tóquio', 'e as oito perguntas'] }, { cue: 'No último episódio, a gente vai até lá...' })
];

/* ====================================================================
 * PARTE 3 — A SEGUNDA ÁGUIA
 * ==================================================================== */
const PERGUNTAS = [
  { t: 'Posso falar com ex-integrantes?', tl: ['Posso falar com', 'ex-integrantes?'], curto: 'Ex-integrantes', d: ['Inclusive com os insatisfeitos?'] },
  { t: 'O que acontece se eu sair?', tl: ['O que acontece', 'se eu sair?'], curto: 'Se eu sair', d: ['Perco dinheiro, bens, amigos?'] },
  { t: 'Para onde vai o dinheiro?', tl: ['Para onde vai', 'o dinheiro?'], curto: 'O dinheiro', d: ['Existe balanço público?', 'Quem é o dono, no papel?'] },
  { t: 'A quem o líder presta contas?', tl: ['A quem o líder', 'presta contas?'], curto: 'Prestação de contas', d: ['Existe um canal de denúncia', 'que não passe por ele?'] },
  { t: 'O que se ensina lá em cima?', tl: ['O que se ensina', 'lá em cima?'], curto: 'Níveis de cima', d: ['Posso ver o material antes de pagar?'] },
  { t: 'Quanto custa tudo?', tl: ['Quanto custa o', 'programa inteiro?'], curto: 'Custo total', d: ['Do primeiro ao último nível.'] },
  { t: 'Já foi citada em processo?', tl: ['Já foi citada', 'em processo?'], curto: 'Relatórios e processos', d: ['Em relatório oficial ou em processo?', 'E o que respondeu?'] },
  { t: 'Posso anotar e gravar?', tl: ['Posso anotar', 'e gravar?'], curto: 'Anotar e gravar', d: ['E mostrar o material a quem eu quiser?'] }
];
const PERG_CUES = ['A primeira: posso conversar com ex-integrantes...', 'A segunda: o que acontece se eu sair?', 'A terceira: para onde vai o dinheiro?', 'A quarta: a quem o líder presta contas?', 'A quinta: o que se ensina nos níveis de cima?', 'A sexta: quanto custa o programa inteiro?', 'A sétima: a organização já foi citada em relatório oficial ou em processo?', 'A oitava: posso anotar, gravar e mostrar o material a quem eu quiser?'];

const EP3 = [
  T('cassete', 'fitas-cassete', 11, {}, { cue: 'Em 1992, no litoral do Paraná, a polícia gravou em fitas cassete as confissões... Elas diziam outra coisa.', fonte: 'Revisão criminal, TJPR (2023); Projeto Humanos', cat: 'judicial', somber: true }),
  T('titulo', 'titulo-parte-3', 6, { parte: 'PARTE 3', sub: 'A SEGUNDA ÁGUIA' }, { cue: 'Logo depois do gancho de abertura (cartela de título).' }),
  T('itens', 'nos-episodios-anteriores', 11, { kicker: 'Nos episódios anteriores', itens: ['a porta de entrada e os andares de cima', 'pé na porta, vocabulário, segredo, comissão, chalé', 'uniformes, brigadas e um juramento diante de uma águia', 'Buenos Aires, Abadiânia, Maranhão e Shakahola', 'escolha limitada: a versão chata da lavagem cerebral'], size: 44, y0: 350 }, { cue: 'Nos dois primeiros episódios, a gente atravessou a porta de entrada e subiu os andares.' }),

  cap('I', ['Os caçadores'], 'Antes do Paraná, uma escala nos Estados Unidos.'),
  nome('ted-patrick', 'Ted Patrick', 'desprogramador · anos 1970', 'O mais famoso foi Ted Patrick.'),
  T('fluxo', 'desprogramacao', 10, { kicker: 'DESPROGRAMAÇÃO, ANOS 1970', etapas: [{ t: ['A FAMÍLIA', 'PAGA'] }, { t: ['ABORDAGEM', 'NA RUA'] }, { t: ['UM', 'CARRO'] }, { t: ['QUARTO', 'DE MOTEL'] }, { t: ['ATÉ', 'RENUNCIAR'], destaque: true }], nota: 'O método de Lifton, com diária de motel.' }, { cue: 'O método era direto. A família pagava. A equipe abordava o filho na rua, colocava num carro...' }),
  T('leilao', 'leilao-cult-awareness-network', 10, { kicker: 'SCOTT CONTRA ROSS · JUSTIÇA FEDERAL DOS EUA · 1995', titulo: ['Indenização milionária.', 'A rede antisseitas quebra.'], lotes: [['O NOME'], ['O LOGOTIPO'], ['A LINHA', 'TELEFÔNICA']], nota: 'Arrematados no leilão da falência por um membro da Cientologia.' }, { cue: 'A rede quebrou. No leilão da falência, o nome, o logotipo e a linha telefônica foram arrematados por um membro da Cientologia.' }),
  T('destaque', 'artigo-148', 9, { kicker: 'No Brasil', linhas: ['Desprogramar à força:', '[sequestro e cárcere privado],', 'artigo 148 do Código Penal.'], nota: ['Pena maior quando a vítima é filho, pai ou cônjuge de quem comete o crime.', 'Exatamente o perfil de quem contrata um desprogramador.'], size: 88 }, { cue: 'No Brasil, desprogramar alguém à força tem nome no Código Penal: sequestro e cárcere privado, artigo 148.' }),

  cap('II', ['Guaratuba'], 'Guaratuba, litoral do Paraná. Segunda-feira, 6 de abril de 1992.', true),
  T('dateline', 'dateline-guaratuba', 9, { lugar: 'GUARATUBA · PARANÁ', data: '06.04.1992', sub: ['Evandro Ramos Caetano, seis anos, desaparece.', 'Cinco dias depois, o corpo é encontrado.'] }, { cue: 'Evandro Ramos Caetano, de seis anos, desaparece. Cinco dias depois, o corpo é encontrado num matagal.', somber: true }),
  O('aguias', 'contador-aguias-2', 6, { n: 2 }, { cue: 'No começo de julho, um grupo da Polícia Militar do Paraná entra no caso. O nome dele era Grupo Águia.' }),
  T('comparacao', 'magia-negra-de-volta', 10, { esq: { titulo: 'Museu da polícia · 1890–1940', itens: [['MAGIA', 'NEGRA']], size: 120 }, dir: { titulo: 'Tese da acusação · 1992', itens: [['MAGIA', 'NEGRA']], size: 120 }, rodape: 'Em 1992, a expressão voltou à primeira página. E, entre os presos, havia um pai de santo.' }, { cue: 'Durante meio século, o Estado brasileiro guardou objetos de terreiro numa coleção chamada Magia Negra... Em 1992, a expressão voltou à primeira página.', somber: true }),
  T('linhatempo', 'linha-do-tempo-caso-evandro', 13, { titulo: 'Caso Evandro', anoSize: 54, txtSize: 22, eventos: [{ ano: '1992', txt: ['sete presos;', 'confissões', 'gravadas em fita'] }, { ano: '1998', txt: ['1º júri: 34 dias;', 'absolvição,', 'depois anulada'] }, { ano: 'ATÉ 2011', txt: ['júris seguintes:', 'quatro condenações,', 'duas absolvições'] }, { ano: '2018', txt: ['Projeto Humanos', 'começa a contar', 'o caso'] }, { ano: '2023', txt: ['TJPR: revisão', 'criminal procedente,', '3 votos a 2'], destaque: true }, { ano: '2026', txt: ['STF: trânsito', 'em julgado', '(31 de março)'] }] }, { cue: 'Vieram cinco júris, entre 1998 e 2011... Em 31 de março de 2026, o STF declarou o trânsito em julgado.', fonte: 'TJPR (2023); STF (2026); Projeto Humanos', cat: 'judicial', somber: true }),
  nome('ivan-mizanzuk', 'Ivan Mizanzuk', 'professor e podcaster · Projeto Humanos', 'Em 2018, o professor Ivan Mizanzuk começou a contar o caso no podcast Projeto Humanos.'),
  T('itens', 'decisao-tjpr', 11, { kicker: 'TJPR · 09.11.2023 · revisão criminal', titulo: ['Procedente,', 'por 3 votos a 2'], itens: ['Beatriz Abagge', 'Osvaldo Marcineiro', 'Davi dos Santos Soares', 'Vicente de Paula Ferreira (depois de morto)'], size: 50, nota: 'Absolvidos. O tribunal mandou apurar a conduta de quem torturou.' }, { cue: 'Em 9 de novembro de 2023, por três votos a dois, o Tribunal de Justiça do Paraná julgou procedente a revisão criminal.', fonte: 'Tribunal de Justiça do Paraná, 09/11/2023', cat: 'judicial', somber: true }),
  T('numeros', 'trinta-e-um-anos-definitivo', 9, { itens: [{ v: 31, suf: ' anos', label: ['do crime à revisão', 'criminal (1992–2023)'] }, { texto: '31.03.2026', label: ['decisão definitiva', '(trânsito em julgado no STF)'] }], size: 200, nota: 'O assassinato de um menino de seis anos continua, oficialmente, sem autor.' }, { cue: 'Trinta e um anos depois... O assassinato de um menino de seis anos continua, oficialmente, sem autor.', fonte: 'STF, trânsito em julgado em 31/03/2026', cat: 'judicial', somber: true }),
  T('duasaguias', 'duas-aguias', 11, { esq: { titulo: 'ÁGUIA 1', sub: 'a “Águila Solar”', itens: [['cerimônia relatada por ex-integrante', '(El Español, 2022)'], ['a organização nega essa descrição'], ['nunca condenada por isso']] }, dir: { titulo: 'ÁGUIA 2', sub: 'o Grupo Águia (PM-PR)', itens: [['caçava uma seita'], ['as pessoas que prendeu'], ['foram absolvidas em definitivo']] } }, { cue: 'A primeira águia desta série aparece num grupo que ex-integrantes descrevem como seita... A segunda pertencia a quem estava caçando uma seita.' }),
  loop('marcador-cacadores-respondido', 'fechado', '02', ['O erro foi achar que a palavra bastava.'], 'O erro foi achar que a palavra bastava.'),

  cap('III', ['O que os', 'tribunais', 'conseguem ver'], 'No episódio anterior, eu prometi os tribunais da Nova Acrópole.'),
  T('citacao', 'citacao-tgi-paris-1982', 11, { linhas: ['Não por sua atividade cultural', 'verdadeira, mas por textos de uso', 'interno escritos por seu fundador.'], autor: ['— Tribunal de Grande Instância de Paris, 10/11/1982 (tradução livre)', 'A Nova Acrópole perde a ação por difamação contra Alain Woodrow (Le Monde).'], cat: 'judicial', size: 68, destaque: ['interno'] }, { cue: 'Paris, 1982. A Nova Acrópole processa por difamação o jornalista Alain Woodrow, do Le Monde, e perde.', fonte: 'Tribunal de Grande Instância de Paris, 10/11/1982', cat: 'judicial' }),
  T('placar', 'placar-um-a-um', 8, { titulo: 'NOVA ACRÓPOLE NA JUSTIÇA FRANCESA · DIFAMAÇÃO', esq: { ano: '1982', caso: ['contra Alain Woodrow,', 'do Le Monde'], resultado: 'PERDE', cor: 'red' }, dir: { ano: '1997', caso: ['contra Miguel Martinez', 'e o Canal Plus'], resultado: 'GANHA', cor: 'amber' }, nota: 'Empate não cabe em thumbnail.' }, { cue: 'Placar: um a um. Quem procura um veredito simples sobre a Nova Acrópole na Justiça francesa encontra um empate.', fonte: 'TGI de Paris, 10/11/1982 e 02/07/1997', cat: 'judicial' }),
  T('itens', 'notas-de-rodape', 12, { kicker: 'Notas de rodapé', f: 'mono', size: 46, gap: 150, y0: 360, itens: [['Lista parlamentar francesa de 1995 (172 movimentos):', 'declarada obsoleta pelo próprio governo em 2005.'], ['Madri, 1988: o fundador é julgado por posse ilegal de armas.', 'Fontes secundárias falam em condenação; acórdão não visto.'], ['Brasil: nenhuma ação judicial nem relatório oficial', 'localizado sobre a Nova Acrópole.']] }, { cue: 'Há mais duas notas de rodapé. A lista parlamentar francesa de 1995... foi declarada obsoleta pelo próprio governo em 2005.' }),
  T('itens', 'pro-vida-na-justica', 10, { kicker: 'Pró-Vida na Justiça', f: 'mono', size: 46, gap: 150, y0: 360, itens: [['Ação da sócia das 2h30, pedindo cerca de US$ 50 mil:', 'resultado não encontrado.'], ['TJSP, 2019: anulação de exclusão e danos morais:', 'desfecho não encontrado.'], ['Condenação do movimento: nenhuma.']] }, { cue: 'A Pró-Vida também não tem condenação. E a sócia das duas e meia da manhã? Ela processou o movimento...' }),
  T('destaque', 'codigo-civil-chale', 11, { kicker: 'Código Civil · arts. 57 e 884', linhas: ['Associado só é excluído por [justa causa],', 'com direito de [defesa] e de [recurso].', 'E é proibido o [enriquecimento sem causa].'], size: 76, nota: ['O Código Civil não sabe o que é Tela Mental.', 'Mas sabe muito bem o que é um chalé.'] }, { cue: 'O artigo 57 do Código Civil diz que um associado só pode ser excluído por justa causa... O Código Civil não sabe o que é Tela Mental.' }),

  cap('IV', ['Recibos'], 'Falta um tribunal: o de Tóquio, prometido lá no primeiro episódio.'),
  T('dateline', 'dateline-nara-2022', 8, { lugar: 'NARA · JAPÃO', data: '08.07.2022', sub: ['O ex-primeiro-ministro Shinzo Abe é morto a tiros num comício.', 'O atirador diz que queria atingir a Igreja da Unificação.'] }, { cue: 'Julho de 2022. O ex-primeiro-ministro japonês Shinzo Abe é morto a tiros durante um comício.', somber: true }),
  selo('imprensa-japonesa', 'reportagem', 'Imprensa japonesa · 2022', 'Segundo a imprensa japonesa, a mãe dele tinha doado à igreja cerca de 100 milhões de ienes...'),
  T('linhatempo', 'linha-do-tempo-japao', 12, { titulo: 'Igreja da Unificação no Japão', anoSize: 50, eventos: [{ ano: 'DEZ. 2022', txt: ['lei contra a', 'solicitação abusiva', 'de doações'] }, { ano: '2023', txt: ['governo pede', 'a dissolução'] }, { ano: 'MAR. 2025', txt: ['Tribunal Distrital', 'de Tóquio dissolve'] }, { ano: 'MAR. 2026', txt: ['Tribunal Superior', 'confirma'] }, { ano: '22.06.2026', txt: ['Suprema Corte', 'rejeita o último', 'recurso'], destaque: true }] }, { cue: 'Em dezembro de 2022, o Japão aprovou uma lei contra a solicitação abusiva de doações...', fonte: 'Decisões judiciais japonesas (2025–2026); Yomiuri', cat: 'judicial' }),
  T('recibo', 'recibo-dissolucao', 10, { linhas: ['================================', '  IGREJA DA UNIFICAÇÃO · JAPÃO', '================================', 'PEDIDOS DE DOAÇÃO', 'CONSIDERADOS ILEGAIS ......  SIM', 'PERÍODO ........ 1973 A 2022', 'TOTAL ................ 49 ANOS', 'LAVAGEM CEREBRAL PROVADA ..  NÃO', 'SEITA DEFINIDA ............  NÃO', 'MESSIAS CONFIRMADO ........  NÃO', '--------------------------------', '!SUPREMA CORTE · 22/06/2026'], carimbo: 'DISSOLVIDA', nota: 'Ilustração. Fonte: decisões judiciais japonesas (2025–2026).' }, { cue: 'Não precisou provar lavagem cerebral... O grupo mais associado a lavagem cerebral no século 20 caiu pelo argumento mais tedioso do Direito: o recibo.' }),
  selo('lamentavel-e-injusta', 'org', 'Igreja da Unificação, sobre a 1ª decisão: “lamentável e injusta”', 'Sobre a primeira decisão, a igreja disse que ela era "lamentável e injusta".'),
  T('destaque', 'lei-francesa-2024', 10, { kicker: 'França · Lei nº 2024-420 · maio de 2024', linhas: ['Crime: [colocar] ou [manter] alguém', 'em estado de sujeição', 'psicológica ou física.'], size: 92, nota: ['O crime não é pertencer a uma seita.', 'A lei não traz lista de grupos. Traz comportamentos.'] }, { cue: 'A França chegou ao mesmo lugar por outro caminho. Uma lei de maio de 2024 criou o crime de colocar ou manter alguém em estado de sujeição...' }),
  T('itens', 'artigos-brasileiros', 12, { kicker: 'No Brasil não existe crime de seita. Mas existe:', itens: ['art. 171 · estelionato', 'art. 215 · violação sexual mediante fraude', 'art. 149 · trabalho análogo ao de escravo', 'art. 147-A · perseguição', 'art. 147-B · violência psicológica contra a mulher', 'Código Civil · doação sob coação, anulável em até 4 anos'], nota: 'Nenhum desses artigos menciona águias.', y0: 330 }, { cue: 'No Brasil, não existe crime de seita... Mas existe o estelionato, artigo 171 do Código Penal.' }),

  cap('V', ['O pouso'], 'Se você chegou até aqui esperando que eu dissesse qual desses grupos é uma seita...'),
  T('itens', 'tese-comportamentos', 12, { kicker: 'Seita não é um tipo de organização. É um conjunto de comportamentos:', itens: ['engano na entrada', 'escalada de compromisso', 'segredo sobre o que vem depois', 'isolamento', 'controle da informação', 'dinheiro e patrimônio amarrados à permanência', 'punição de quem sai'], numerado: true, y0: 320 }, { cue: 'Seita não é um tipo de organização. É um conjunto de comportamentos. Engano na entrada...' }),
  T('barras', 'miviludes-denuncias', 8, { titulo: 'Denúncias à Miviludes (França)', itens: [{ label: ['2015'], v: 2160 }, { label: ['2024'], v: 4571, cor: 'red' }], xBar: 400 }, { cue: 'Segundo o relatório de atividade da Miviludes, as denúncias... passaram de 2.160 em 2015 para 4.571 em 2024.', fonte: 'Miviludes, relatório de atividade 2022–2024', cat: 'oficial' }),
  T('barras', 'miviludes-categorias', 8, { titulo: 'Denúncias por área, 2024', itens: [{ label: ['saúde e', 'bem-estar'], v: 37, suf: '%', cor: 'red' }, { label: ['cultos e', 'espiritualidades'], v: 35, suf: '%' }], max: 40, nota: 'A primeira categoria já não é religião.' }, { cue: 'E a primeira categoria já não é religião. É saúde e bem-estar, com 37% das denúncias...', fonte: 'Miviludes, relatório de atividade 2022–2024', cat: 'oficial' }),
  T('celular', 'curso-introdutorio-de-hoje', 9, {}, { cue: 'O curso introdutório não precisa mais de sala. Tem link na bio, contagem regressiva e grupo VIP.' }),

  cap('VI', ['As oito', 'perguntas'], 'Prometi oito perguntas no primeiro episódio. Aqui estão.'),
  loop('marcador-oito-perguntas-respondido', 'fechado', '00', ['As oito perguntas'], 'Prometi oito perguntas no primeiro episódio. Aqui estão.', 5),
  ...PERGUNTAS.map((o, i) => T('lista8', `pergunta-${i + 1}`, 6, { titulo: 'As oito perguntas', itens: PERGUNTAS, ativo: i + 1 }, { cue: PERG_CUES[i] })),
  T('lista8', 'perguntas-visao-geral', 8, { titulo: 'As oito perguntas', itens: PERGUNTAS, ativo: 0 }, { cue: 'Repare que nenhuma pergunta é sobre crença.' }),
  T('destaque', 'grupo-que-nao-responde', 9, { kicker: 'Nenhuma pergunta é sobre crença', linhas: ['Um grupo saudável responde', 'às oito [sem levantar a voz].', 'Um grupo que não responde', '[já respondeu].'], size: 96 }, { cue: 'Um grupo saudável responde às oito sem levantar a voz. Um grupo que não responde já respondeu.' }),
  T('checklist', 'teste-do-canal', 12, { titulo: 'As oito perguntas, aplicadas a este canal', size: 44, gap: 78, itens: [{ t: 'Ex-espectadores insatisfeitos', s: 'nos comentários' }, { t: 'Se você sair', s: 'perde o próximo vídeo' }, { t: 'Para onde vai o dinheiro', s: 'anúncios e membros' }, { t: 'A quem presta contas', s: 'a um algoritmo' }, { t: 'O material', s: 'fontes na descrição' }, { t: 'Custo total', s: '1 hora, em 3 parcelas' }, { t: 'Relatório oficial sobre o canal', s: 'por enquanto, não' }, { t: 'Pode anotar e gravar', s: 'por favor, anote' }] }, { cue: 'Eu disse que elas funcionavam contra este canal. Vamos lá.' }),
  T('comparacao', 'como-ajudar', 11, { esq: { titulo: 'Não faça', cor: 'red', itens: ['ridicularizar', 'dar ultimato', 'cortar contato', 'despejar um dossiê', 'usar força'], size: 56 }, dir: { titulo: 'Faça', itens: ['manter o vínculo', 'perguntas abertas', 'ouvir as respostas', 'documentar, se for você'], size: 56 }, riscarEsq: true, passo: 0.3, rodape: 'A família é a ponte de volta.' }, { cue: 'Não ridicularize. Não dê ultimato. Não corte contato. A família é a ponte de volta...' }),
  T('itens', 'perguntas-abertas', 9, { kicker: 'Perguntas abertas', f: 'serif', size: 64, gap: 110, y0: 400, itens: ['“O que você mais gosta lá?”', '“Como eles lidam com quem discorda?”', '“O que aconteceria se você quisesse sair?”'] }, { cue: 'Faça perguntas abertas e ouça as respostas. "O que você mais gosta lá?"' }),
  T('contatos', 'canais-de-ajuda', 12, { itens: [{ t: ['CVV'], s: ['188 · apoio emocional,', '24 horas'] }, { t: ['DISQUE', '100'], s: ['direitos humanos'] }, { t: ['LIGUE', '180'], s: ['violência contra', 'a mulher'] }, { t: ['MINISTÉRIO', 'PÚBLICO'], s: ['denúncia de crimes'] }, { t: ['DEFENSORIA', 'PÚBLICA'], s: ['orientação jurídica', 'gratuita'] }] }, { cue: 'E, se houver violência, exploração ou risco, existem canais que não cobram curso introdutório...' }),
  T('checklist', 'por-que-ela-foi-acordada', 9, { titulo: 'Por que ela foi acordada às 2h30', itens: [{ t: 'Acreditar em pirâmides', ok: false, s: 'não' }, { t: 'Fazer a Tela Mental do jeito errado', ok: false, s: 'não' }, { t: 'Atrasar o dízimo', ok: false, s: 'não' }, { t: 'Conversar com alguém de fora', s: 'sim' }] }, { cue: 'Lembra da sócia das duas e meia da manhã? Ela não foi acordada por acreditar em pirâmides... (antes, reaproveite E1-01)' }),
  T('portas', 'porta-de-entrada-porta-de-saida', 10, {}, { cue: 'A seita, quando existe, não fica na porta de entrada. Fica na de saída. A de entrada tem café.' }),
  T('titulo', 'fim-da-serie', 7, { parte: 'FIM DA SÉRIE', sub: 'AS FONTES ESTÃO NA DESCRIÇÃO' }, { cue: 'Encerramento (depois da última frase).' })
];

function numerar(ep, arr) {
  return arr.map((c, i) => ({ ...c, ep, id: `E${ep}-${String(i + 1).padStart(2, '0')}` }));
}

export default [...numerar(1, EP1), ...numerar(2, EP2), ...numerar(3, EP3)];
